[package]
name = "aion-program"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = "0.1.44"
rand = { version = "0.10.0" }

small_derive_deref = "0.1.4"

aion-state = { path = "../aion-state" }

hecs = "0.11.0"
parking_lot = "0.12.5"
tokio = { version = "1.52.3", features = ["rt"]}
anyhow = "1.0.102"
thiserror = "2.0.18"

[dev-dependencies]
lazy_static = "1.5.0"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }