#![allow(clippy::match_like_matches_macro)]
#![allow(clippy::type_complexity)]
#![allow(clippy::single_match)]

pub mod injection;
pub mod program_registry;
pub mod registry_implementation;

pub mod prelude {
    pub use super::{
        injection::{
            Injection,
            access_builder::{
                AccessBuilder
            },
            finalised_access::{
                FinalisedAccess
            },
            resolve_resource_error::{
                ResolveResourceError
            },
            derived_resource::{
                DerivedResource,
            },
        },
        program_registry::{
            ProgramRegistry,
            prompted_program_access::{
                PromptedProgramAccess
            },
            derived_result::{
                DerivedResult
            },
            resolved_resource::{
                ResolvedResource,
                casted_resource::{
                    CastedResource
                }
            },
            program_id::{
                ProgramId
            },
            program_access::{
                ProgramAccess
            },
            stored_program::{
                StoredProgram,
                program::{
                    Program,
                    resource_access::{
                        ResourceAccess
                    },
                    resource_id::{
                        ResourceId
                    },
                    stored_resource::{
                        StoredResource,
                        resource::{
                            Resource
                        }
                    }
                }
            }
        },
        registry_implementation::{
            storages::{
                access_storage::{
                    AccessStorage,
                },
                blacklist_storage::{
                    BlacklistStorage,
                },
                control_storage::{
                    ControlStorage
                },
                credential_storage::{
                    CredentialStorage
                },
                registry_storage::{
                    RegistryStorage
                },
                reserver_storage::{
                    ReservationStorage
                },
                whitelist_storage::{
                    WhitelistStorage
                }
            },
            primitives::{
                value_password::{
                    ValuePassword
                },
                user_id::{
                    UserId
                },
                user_password::{
                    UserPassword
                },
                access_result::{
                    AccessResult
                },
                borrow_type::{
                    BorrowType
                }
            }
        }
    };
}